server:
    port: 8082
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Ahpwg5pBGnr_1
        url: jdbc:mysql://localhost:3306/myDB?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
